// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: protos/server/theatre/theatre.proto

package theatre

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Theatre struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address    string      `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Auditorium *Auditorium `protobuf:"bytes,4,opt,name=auditorium,proto3" json:"auditorium,omitempty"`
}

func (x *Theatre) Reset() {
	*x = Theatre{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_server_theatre_theatre_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Theatre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Theatre) ProtoMessage() {}

func (x *Theatre) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_theatre_theatre_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Theatre.ProtoReflect.Descriptor instead.
func (*Theatre) Descriptor() ([]byte, []int) {
	return file_protos_server_theatre_theatre_proto_rawDescGZIP(), []int{0}
}

func (x *Theatre) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Theatre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Theatre) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Theatre) GetAuditorium() *Auditorium {
	if x != nil {
		return x.Auditorium
	}
	return nil
}

type Auditorium struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	IdMovies string   `protobuf:"bytes,2,opt,name=idMovies,proto3" json:"idMovies,omitempty"`
	Schedule string   `protobuf:"bytes,3,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Seats    []*Seats `protobuf:"bytes,4,rep,name=seats,proto3" json:"seats,omitempty"`
}

func (x *Auditorium) Reset() {
	*x = Auditorium{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_server_theatre_theatre_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Auditorium) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auditorium) ProtoMessage() {}

func (x *Auditorium) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_theatre_theatre_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auditorium.ProtoReflect.Descriptor instead.
func (*Auditorium) Descriptor() ([]byte, []int) {
	return file_protos_server_theatre_theatre_proto_rawDescGZIP(), []int{1}
}

func (x *Auditorium) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Auditorium) GetIdMovies() string {
	if x != nil {
		return x.IdMovies
	}
	return ""
}

func (x *Auditorium) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *Auditorium) GetSeats() []*Seats {
	if x != nil {
		return x.Seats
	}
	return nil
}

type Seats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seat   string  `protobuf:"bytes,2,opt,name=seat,proto3" json:"seat,omitempty"`
	Cost   float32 `protobuf:"fixed32,3,opt,name=cost,proto3" json:"cost,omitempty"`
	Status bool    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Seats) Reset() {
	*x = Seats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_server_theatre_theatre_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Seats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seats) ProtoMessage() {}

func (x *Seats) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_theatre_theatre_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seats.ProtoReflect.Descriptor instead.
func (*Seats) Descriptor() ([]byte, []int) {
	return file_protos_server_theatre_theatre_proto_rawDescGZIP(), []int{2}
}

func (x *Seats) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

func (x *Seats) GetCost() float32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Seats) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type GetTheatreByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTheatreByIdRequest) Reset() {
	*x = GetTheatreByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_server_theatre_theatre_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTheatreByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTheatreByIdRequest) ProtoMessage() {}

func (x *GetTheatreByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_theatre_theatre_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTheatreByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTheatreByIdRequest) Descriptor() ([]byte, []int) {
	return file_protos_server_theatre_theatre_proto_rawDescGZIP(), []int{3}
}

func (x *GetTheatreByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTheatreByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Theatre *Theatre `protobuf:"bytes,1,opt,name=theatre,proto3" json:"theatre,omitempty"`
}

func (x *GetTheatreByIdResponse) Reset() {
	*x = GetTheatreByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_server_theatre_theatre_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTheatreByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTheatreByIdResponse) ProtoMessage() {}

func (x *GetTheatreByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_theatre_theatre_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTheatreByIdResponse.ProtoReflect.Descriptor instead.
func (*GetTheatreByIdResponse) Descriptor() ([]byte, []int) {
	return file_protos_server_theatre_theatre_proto_rawDescGZIP(), []int{4}
}

func (x *GetTheatreByIdResponse) GetTheatre() *Theatre {
	if x != nil {
		return x.Theatre
	}
	return nil
}

var File_protos_server_theatre_theatre_proto protoreflect.FileDescriptor

var file_protos_server_theatre_theatre_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x74, 0x68, 0x65, 0x61, 0x74, 0x72, 0x65, 0x2f, 0x74, 0x68, 0x65, 0x61, 0x74, 0x72, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x7b, 0x0a,
	0x07, 0x54, 0x68, 0x65, 0x61, 0x74, 0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x32, 0x0a, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x74, 0x6f,
	0x72, 0x69, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x75, 0x6d, 0x52, 0x0a,
	0x61, 0x75, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x75, 0x6d, 0x22, 0x7d, 0x0a, 0x0a, 0x41, 0x75,
	0x64, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x73, 0x65, 0x61, 0x74, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x65, 0x61,
	0x74, 0x73, 0x52, 0x05, 0x73, 0x65, 0x61, 0x74, 0x73, 0x22, 0x47, 0x0a, 0x05, 0x53, 0x65, 0x61,
	0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x73, 0x65, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x68, 0x65, 0x61, 0x74, 0x72, 0x65,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x54, 0x68, 0x65, 0x61, 0x74, 0x72, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x74, 0x68, 0x65, 0x61, 0x74, 0x72, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x54, 0x68, 0x65, 0x61, 0x74, 0x72, 0x65, 0x52, 0x07, 0x74, 0x68, 0x65, 0x61, 0x74, 0x72, 0x65,
	0x32, 0x63, 0x0a, 0x0e, 0x54, 0x68, 0x65, 0x61, 0x74, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x51, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x68, 0x65, 0x61, 0x74, 0x72, 0x65,
	0x42, 0x79, 0x49, 0x64, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x68, 0x65, 0x61, 0x74, 0x72, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x68, 0x65, 0x61, 0x74, 0x72, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x17, 0x5a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x74, 0x68, 0x65, 0x61, 0x74, 0x72, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_server_theatre_theatre_proto_rawDescOnce sync.Once
	file_protos_server_theatre_theatre_proto_rawDescData = file_protos_server_theatre_theatre_proto_rawDesc
)

func file_protos_server_theatre_theatre_proto_rawDescGZIP() []byte {
	file_protos_server_theatre_theatre_proto_rawDescOnce.Do(func() {
		file_protos_server_theatre_theatre_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_server_theatre_theatre_proto_rawDescData)
	})
	return file_protos_server_theatre_theatre_proto_rawDescData
}

var file_protos_server_theatre_theatre_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_server_theatre_theatre_proto_goTypes = []interface{}{
	(*Theatre)(nil),                // 0: protos.Theatre
	(*Auditorium)(nil),             // 1: protos.Auditorium
	(*Seats)(nil),                  // 2: protos.Seats
	(*GetTheatreByIdRequest)(nil),  // 3: protos.GetTheatreByIdRequest
	(*GetTheatreByIdResponse)(nil), // 4: protos.GetTheatreByIdResponse
}
var file_protos_server_theatre_theatre_proto_depIdxs = []int32{
	1, // 0: protos.Theatre.auditorium:type_name -> protos.Auditorium
	2, // 1: protos.Auditorium.seats:type_name -> protos.Seats
	0, // 2: protos.GetTheatreByIdResponse.theatre:type_name -> protos.Theatre
	3, // 3: protos.TheatreService.GetTheatreById:input_type -> protos.GetTheatreByIdRequest
	4, // 4: protos.TheatreService.GetTheatreById:output_type -> protos.GetTheatreByIdResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_server_theatre_theatre_proto_init() }
func file_protos_server_theatre_theatre_proto_init() {
	if File_protos_server_theatre_theatre_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_server_theatre_theatre_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Theatre); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_server_theatre_theatre_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Auditorium); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_server_theatre_theatre_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Seats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_server_theatre_theatre_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTheatreByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_server_theatre_theatre_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTheatreByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_server_theatre_theatre_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_server_theatre_theatre_proto_goTypes,
		DependencyIndexes: file_protos_server_theatre_theatre_proto_depIdxs,
		MessageInfos:      file_protos_server_theatre_theatre_proto_msgTypes,
	}.Build()
	File_protos_server_theatre_theatre_proto = out.File
	file_protos_server_theatre_theatre_proto_rawDesc = nil
	file_protos_server_theatre_theatre_proto_goTypes = nil
	file_protos_server_theatre_theatre_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TheatreServiceClient is the client API for TheatreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TheatreServiceClient interface {
	GetTheatreById(ctx context.Context, in *GetTheatreByIdRequest, opts ...grpc.CallOption) (*GetTheatreByIdResponse, error)
}

type theatreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTheatreServiceClient(cc grpc.ClientConnInterface) TheatreServiceClient {
	return &theatreServiceClient{cc}
}

func (c *theatreServiceClient) GetTheatreById(ctx context.Context, in *GetTheatreByIdRequest, opts ...grpc.CallOption) (*GetTheatreByIdResponse, error) {
	out := new(GetTheatreByIdResponse)
	err := c.cc.Invoke(ctx, "/protos.TheatreService/GetTheatreById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TheatreServiceServer is the server API for TheatreService service.
type TheatreServiceServer interface {
	GetTheatreById(context.Context, *GetTheatreByIdRequest) (*GetTheatreByIdResponse, error)
}

// UnimplementedTheatreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTheatreServiceServer struct {
}

func (*UnimplementedTheatreServiceServer) GetTheatreById(context.Context, *GetTheatreByIdRequest) (*GetTheatreByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTheatreById not implemented")
}

func RegisterTheatreServiceServer(s *grpc.Server, srv TheatreServiceServer) {
	s.RegisterService(&_TheatreService_serviceDesc, srv)
}

func _TheatreService_GetTheatreById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTheatreByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheatreServiceServer).GetTheatreById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.TheatreService/GetTheatreById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheatreServiceServer).GetTheatreById(ctx, req.(*GetTheatreByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TheatreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.TheatreService",
	HandlerType: (*TheatreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTheatreById",
			Handler:    _TheatreService_GetTheatreById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/server/theatre/theatre.proto",
}
